[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
scripts_are_modules = true
implicit_reexport = false
warn_unused_ignores = true
check_untyped_defs = true
warn_redundant_casts = true
ignore_missing_imports = true

[tool.coverage.run]
omit = [
    "dyntastic/pydantic_compat.py",
]

[tool.coverage.report]
exclude_also = [
    "@overload",
]
